### ISSUE TITLE
Peer Review by Yanyu Long

### ISSUE THREAD

**Issue by longyyu** [yawenh/Stats506_finalproject#1]
Hi Yawen, 

Great job and nicely formatted report! I really enjoyed reading it. Below are some suggestions for you to further improve your work. 
****

* Basic Requirements - all fulfilled. 

* Introduction
    1. I think the description of the analysis can be more succinct and more high-level (for example, mentioning replicate weights may be too detailed and can be saved for the methods section). 

* Data / Methods
    1. There is a typo in step 1 -- "Read in the who CBECS data" -- should be "whole"?

* Results
    1. For table 1, it may be more intuitive to rearrange to columns and put `1980-` in front of `1980+`. 
    1. The proportions displayed in table 1 are multiplied by 100, but those in the figures are still within range [0, 1]. It would be better if the units can be consistent. 
    1. Although the quotas for graphical and tabular elements are already used up, there should be a table with descriptive statistics about the sample according to the rubric (not sure if this is mandatory). 

* Conclusion
    1. The strengths and limitations of the analysis have not been discussed yet. 
    1. This sentence seems to be incomplete: "The use of inside boilers in cold region and mixed-humid region."

* Code
    1. The way you compute variance (`v = mean({prop_rw - prop}^2) / {{1 - 0.5}^2}`) would be correct if we were using the RECS data, but with the CBECS data, the variance is estimated using a different formula. Please refer to this [documentation](https://www.eia.gov/consumption/commercial/data/2012/pdf/user_guide_public_use_aug2016.pdf). 
    1. Since the computation for `MAINCL` and `MAINHT` is very similar, wrapping up the computation into a function would help reduce repetitive code. 
****

Good luck with the project!

**Comment by yawenh** [comment]
Thanks! I'll work on it!
